[package]
name = "shopify_function_trampoline"
version = "2.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/Shopify/shopify-function-wasm-api"
homepage = "https://github.com/Shopify/shopify-function-wasm-api"
description = "Tool for augmenting Wasm modules to be compatible with the Shopify Function Wasm API"

[dependencies]
walrus = "0.23.3"
anyhow = "1.0"
clap = { version = "4.5.53", features = ["derive"] }
wasmparser = "0.238.0"

[dev-dependencies]
uuid = { version = "1.18.1", features = ["v4"] }
assert_cmd = "2.1.1"
predicates = "3.1.3"
wat = "1.241.2"
wasmprinter = "0.235.0"
insta = { version = "1.44", features = ["glob"] }
